# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run_0
      shell: bash
      env:
        APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
      run: |
        mkdir -r src/main/resources
        echo -n "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
        echo -n "$GMAIL_CREDENTIALS" > src/main/resources/credentials.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run
      shell: bash
      env:
        APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
      run: |
        mkdir -r resources/main
        echo -n "$APPLICATION_PROPERTIES" > resources/main/application.properties
        echo -n "$GMAIL_CREDENTIALS" > resources/main/credentials.json
        ls -lh resources/main
        java -jar build/libs/expense-automator-0.0.1-SNAPSHOT.jar
